debug: true

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9080/uaa/oauth/token
      userAuthorizationUri: http://localhost:9080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9080/uaa/user

logging:
  level:
    org.springframework.security: DEBUG